User.create!([
  {email: "a@a.com", password: "a", name: "Arnold Palmer"},
  {email: "b@b.com", password: "b", name: "Bob Boucher"},
  {email: "c@c.com", password: "c", name: "Charles Barkley"},
  {email: "d@d.com", password: "d", name: "Danny Divito"},
  {email: "e@e.com", password: "e", name: "Eva Mendez"},
  {email: "f@f.com", password: "f", name: "Fiona Apple"},
  {email: "g@g.com", password: "g", name: "Gary Busey"},
  {email: "h@h.com", password: "h", name: "Harmom Killabrew"},
  {email: "i@i.com", password: "i", name: "Ivanka Trump"},
  {email: "j@j.com", password: "j", name: "Juan Carlos"},
  {email: "k@k.com", password: "k", name: "Kim K"},
  {email: "l@l.com", password: "l", name: "Lamar Odom"},
])
Course.create!([
  {name: "Bidwell Park", par: 72, rating: 68.8, holes: 18, notes: "Bidwell Park Golf Course is one of Northern California's original Municipal Golf Courses. From the natural wilderness of Upper Bidwell Park stems a picturesque 18 hole layout, with the front nine offering a scenic parkland setting, while the back nine is set in the foothills of Bidwell Park. Every September Bidwell Park Golf Course plays host to The Chico City Championship, the second oldest match play tournament in California. This fair but demanding Par 72 course has been serving Northern California since opening in 1929.\r\n"},
  {name: "Tuscan Ridge", par: 71, rating: 68.7, holes: 18, notes: "Tuscan Ridge Golf Club has been recognized as one of Northern California's newest and most unique golf courses to play in the area. Located right between Chico and Paradise, CA it's only a few miles outside of town. Guaranteed to challenge golfers of all skill levels, this par 71, 6434 yard course offers 18 outstanding holes, featuring lush fairways lined with rustic oaks, and expansive greens surrounded by treacherous bunkers. During the round, players can enjoy breathtaking sights of the Sutter Buttes, the skyline of Chico, as well as the Pacific Coast mountain range."},
  {name: "San Juan Hills", par: 72, rating: 70.7, holes: 18, notes: "The golf course at San Juan Hills Golf Club is truly an oasis for both the serious golfer as well as the vacationing one. Nestled in the rolling hills of San Juan Capistrano, San Juan Hills Golf Club is a Par 71 Championship golf course. Recent improvements in our grounds have resulted in a course that offers the best greens and fairways in south Orange County. Open to the public, you’ll find a game here every day of the week."},
  {name: "San Clemente Municiple", par: 72, rating: 70.2, holes: 18, notes: "The San Clemente Municipal Golf Club is a scenic, family friendly championship 18-hole golf course where Fridays are still weekdays, walkers are still welcome and juniors are always ½ price. Owned and operated by the City of San Clemente, the course is located approximately one mile from the Pacific Ocean and features ocean views from a number of holes. Named “Best Value in Orange County” in 2008, the rolling hills and relaxed atmosphere of the “Muni” have remained popular with local golfers for over seventy five years."},
  {name: "Skyway Golf Park", par: 18, rating: 16.9, holes: 6, notes: "Skyway Golf Park is a six-hole par 3 executive golf course, featuring a 25 station driving range, and a fully-stocked pro shop serving the needs of golfers of all ages and abilities. The course and range are fully lit for practicing and playing during the warm summer nights in Chico, and the early sunsets of winter. Whatever your golfing needs may be, we're certain you will find Skyway Golf to be your destination for quality, affordable golf."},
  {name: "Oceanside Golf Course", par: 72, rating: 69.6, holes: 18, notes: " \nLocated in North County adjacent to Camp Pendleton, minutes away from downtown Oceanside and 15 minutes from Carlsbad.\n\nThe club showcases 18 holes of golf, which is open to the public, with special consideration for Oceanside residents.  Featuring an all grass driving range, a full service grill for a delicious bite to eat during your round of golf, and a bar to enjoy your favorite beverage.\n\nCome experience the spectacular views of the undisturbed hillsides and native habitat of the San Luis Rey Valley during your next visit to Oceanside Golf Course."},
  {name: "Spyglass", par: 18, rating: 72.2, holes: 18, notes: "Spyglass Hill Golf Course takes its theme from Robert Louis Stevenson's classic novel, Treasure Island, published in 1883. Local legend maintains that Stevenson once wandered the Spyglass area gathering ideas for his novels. With this in mind, Robert Trent Jones Sr. set about creating a treasure of his own.\nOpened in 1966, Spyglass Hill Golf Course features two distinctly different kinds of terrain that influence the way the holes look and play. The first five holes roll through sandy seaside dunes challenging you to carefully pick the safest path. The following 13 holes are cut through majestic pines with elevated greens and strategically placed bunkers and lakes to grab the errant shot. Hole names such as Black Dog and Billy Bones are hints for the unwary.\nSpyglass Hill Golf Course is rated one of the toughest courses in the world from the Championship tees, boasting a course rating of 75.5 and a slope rating of 144. The PGA TOUR consistently lists Spyglass Hill holes 6, 8 and 16 among the toughest on the TOUR, and during the 1999 United States Amateur, the stroke average of the field during medal play was in excess of 79."}
])
CourseHole.create!([
  {course_id: 1, number: 1, par: 4, distance: 361, rating: 9, notes: ""},
  {course_id: 1, number: 2, par: 3, distance: 121, rating: 17, notes: ""},
  {course_id: 1, number: 3, par: 4, distance: 369, rating: 11, notes: ""},
  {course_id: 1, number: 4, par: 4, distance: 139, rating: 13, notes: "Grandma got a hole in one!"},
  {course_id: 1, number: 5, par: 5, distance: 499, rating: 3, notes: "Don't be on the right side!"},
  {course_id: 1, number: 6, par: 4, distance: 392, rating: 1, notes: "A drive to the right will have a better look into the green."},
  {course_id: 1, number: 7, par: 3, distance: 139, rating: 15, notes: "Large green, chip close if you come up short."},
  {course_id: 1, number: 8, par: 5, distance: 451, rating: 5, notes: "Beautiful scenery, birdie hole!"},
  {course_id: 1, number: 9, par: 5, distance: 471, rating: 7, notes: "Keep your drive centered as the left and right are OB"},
  {course_id: 1, number: 10, par: 4, distance: 351, rating: 14, notes: "High drives can cut the treeline"},
  {course_id: 1, number: 11, par: 4, distance: 430, rating: 3, notes: ""},
  {course_id: 1, number: 12, par: 3, distance: 168, rating: 3, notes: "Dont hit left!"},
  {course_id: 1, number: 13, par: 4, distance: 357, rating: 8, notes: ""},
  {course_id: 1, number: 14, par: 4, distance: 403, rating: 4, notes: ""},
  {course_id: 1, number: 15, par: 4, distance: 332, rating: 10, notes: ""},
  {course_id: 1, number: 16, par: 3, distance: 150, rating: 18, notes: ""},
  {course_id: 1, number: 17, par: 4, distance: 368, rating: 6, notes: ""},
  {course_id: 1, number: 18, par: 5, distance: 490, rating: 12, notes: ""},
  {course_id: 2, number: 1, par: 4, distance: 370, rating: 10, notes: ""},
  {course_id: 2, number: 2, par: 5, distance: 470, rating: 18, notes: ""},
  {course_id: 2, number: 3, par: 4, distance: 324, rating: 14, notes: ""},
  {course_id: 2, number: 4, par: 4, distance: 277, rating: 16, notes: ""},
  {course_id: 2, number: 5, par: 3, distance: 153, rating: 12, notes: ""},
  {course_id: 2, number: 6, par: 4, distance: 330, rating: 6, notes: ""},
  {course_id: 2, number: 7, par: 3, distance: 171, rating: 8, notes: ""},
  {course_id: 2, number: 8, par: 4, distance: 390, rating: 2, notes: ""},
  {course_id: 2, number: 9, par: 5, distance: 518, rating: 4, notes: ""},
  {course_id: 2, number: 10, par: 5, distance: 396, rating: 3, notes: ""},
  {course_id: 2, number: 11, par: 3, distance: 136, rating: 17, notes: ""},
  {course_id: 2, number: 12, par: 4, distance: 364, rating: 1, notes: ""},
  {course_id: 2, number: 13, par: 3, distance: 142, rating: 13, notes: ""},
  {course_id: 2, number: 14, par: 4, distance: 386, rating: 5, notes: ""},
  {course_id: 2, number: 15, par: 4, distance: 395, rating: 9, notes: ""},
  {course_id: 2, number: 16, par: 3, distance: 134, rating: 15, notes: ""},
  {course_id: 2, number: 17, par: 5, distance: 463, rating: 11, notes: ""},
  {course_id: 2, number: 18, par: 4, distance: 368, rating: 7, notes: ""},
  {course_id: 3, number: 1, par: 4, distance: 370, rating: 10, notes: ""},
  {course_id: 3, number: 2, par: 5, distance: 470, rating: 18, notes: ""},
  {course_id: 3, number: 3, par: 4, distance: 324, rating: 14, notes: ""},
  {course_id: 3, number: 4, par: 4, distance: 277, rating: 16, notes: ""},
  {course_id: 3, number: 5, par: 3, distance: 153, rating: 12, notes: ""},
  {course_id: 3, number: 6, par: 4, distance: 330, rating: 6, notes: ""},
  {course_id: 3, number: 7, par: 3, distance: 171, rating: 8, notes: ""},
  {course_id: 3, number: 8, par: 4, distance: 390, rating: 2, notes: ""},
  {course_id: 3, number: 9, par: 5, distance: 518, rating: 4, notes: ""},
  {course_id: 3, number: 10, par: 5, distance: 396, rating: 3, notes: ""},
  {course_id: 3, number: 11, par: 3, distance: 136, rating: 17, notes: ""},
  {course_id: 3, number: 12, par: 4, distance: 364, rating: 1, notes: ""},
  {course_id: 3, number: 13, par: 3, distance: 142, rating: 13, notes: ""},
  {course_id: 3, number: 14, par: 4, distance: 386, rating: 5, notes: ""},
  {course_id: 3, number: 15, par: 4, distance: 395, rating: 9, notes: ""},
  {course_id: 3, number: 16, par: 3, distance: 134, rating: 15, notes: ""},
  {course_id: 3, number: 17, par: 5, distance: 463, rating: 11, notes: ""},
  {course_id: 3, number: 18, par: 4, distance: 368, rating: 7, notes: ""},
  {course_id: 4, number: 1, par: 4, distance: 370, rating: 10, notes: ""},
  {course_id: 4, number: 2, par: 5, distance: 470, rating: 18, notes: ""},
  {course_id: 4, number: 3, par: 4, distance: 324, rating: 14, notes: ""},
  {course_id: 4, number: 4, par: 4, distance: 277, rating: 16, notes: ""},
  {course_id: 4, number: 5, par: 3, distance: 153, rating: 12, notes: ""},
  {course_id: 4, number: 6, par: 4, distance: 330, rating: 6, notes: ""},
  {course_id: 4, number: 7, par: 3, distance: 171, rating: 8, notes: ""},
  {course_id: 4, number: 8, par: 4, distance: 390, rating: 2, notes: ""},
  {course_id: 4, number: 9, par: 5, distance: 518, rating: 4, notes: ""},
  {course_id: 4, number: 10, par: 5, distance: 396, rating: 3, notes: ""},
  {course_id: 4, number: 11, par: 3, distance: 136, rating: 17, notes: ""},
  {course_id: 4, number: 12, par: 4, distance: 364, rating: 1, notes: ""},
  {course_id: 4, number: 13, par: 3, distance: 142, rating: 13, notes: ""},
  {course_id: 4, number: 14, par: 4, distance: 386, rating: 5, notes: ""},
  {course_id: 4, number: 15, par: 4, distance: 395, rating: 9, notes: ""},
  {course_id: 4, number: 16, par: 3, distance: 134, rating: 15, notes: ""},
  {course_id: 4, number: 17, par: 5, distance: 463, rating: 11, notes: ""},
  {course_id: 4, number: 18, par: 4, distance: 368, rating: 7, notes: ""},
  {course_id: 5, number: 1, par: 3, distance: 156, rating: 2, notes: ""},
  {course_id: 5, number: 2, par: 3, distance: 135, rating: 6, notes: ""},
  {course_id: 5, number: 3, par: 3, distance: 178, rating: 1, notes: ""},
  {course_id: 5, number: 4, par: 3, distance: 137, rating: 5, notes: ""},
  {course_id: 5, number: 5, par: 3, distance: 150, rating: 3, notes: ""},
  {course_id: 5, number: 6, par: 3, distance: 158, rating: 4, notes: ""},
  {course_id: 6, number: 1, par: 4, distance: 370, rating: 10, notes: ""},
  {course_id: 6, number: 2, par: 5, distance: 470, rating: 18, notes: ""},
  {course_id: 6, number: 3, par: 4, distance: 324, rating: 14, notes: ""},
  {course_id: 6, number: 4, par: 4, distance: 277, rating: 16, notes: ""},
  {course_id: 6, number: 5, par: 3, distance: 153, rating: 12, notes: ""},
  {course_id: 6, number: 6, par: 4, distance: 330, rating: 6, notes: ""},
  {course_id: 6, number: 7, par: 3, distance: 171, rating: 8, notes: ""},
  {course_id: 6, number: 8, par: 4, distance: 390, rating: 2, notes: ""},
  {course_id: 6, number: 9, par: 5, distance: 518, rating: 4, notes: ""},
  {course_id: 6, number: 10, par: 5, distance: 396, rating: 3, notes: ""},
  {course_id: 6, number: 11, par: 3, distance: 136, rating: 17, notes: ""},
  {course_id: 6, number: 12, par: 4, distance: 364, rating: 1, notes: ""},
  {course_id: 6, number: 13, par: 3, distance: 142, rating: 13, notes: ""},
  {course_id: 6, number: 14, par: 4, distance: 386, rating: 5, notes: ""},
  {course_id: 6, number: 15, par: 4, distance: 395, rating: 9, notes: ""},
  {course_id: 6, number: 16, par: 3, distance: 134, rating: 15, notes: ""},
  {course_id: 6, number: 17, par: 5, distance: 463, rating: 11, notes: ""},
  {course_id: 6, number: 18, par: 4, distance: 368, rating: 7, notes: ""},
  {course_id: 7, number: 1, par: 4, distance: 370, rating: 10, notes: ""},
  {course_id: 7, number: 2, par: 5, distance: 470, rating: 18, notes: ""},
  {course_id: 7, number: 3, par: 4, distance: 324, rating: 14, notes: ""},
  {course_id: 7, number: 4, par: 4, distance: 277, rating: 16, notes: ""},
  {course_id: 7, number: 5, par: 3, distance: 153, rating: 12, notes: ""},
  {course_id: 7, number: 6, par: 4, distance: 330, rating: 6, notes: ""},
  {course_id: 7, number: 7, par: 3, distance: 171, rating: 8, notes: ""},
  {course_id: 7, number: 8, par: 4, distance: 390, rating: 2, notes: ""},
  {course_id: 7, number: 9, par: 5, distance: 518, rating: 4, notes: ""},
  {course_id: 7, number: 10, par: 5, distance: 396, rating: 3, notes: ""},
  {course_id: 7, number: 11, par: 3, distance: 136, rating: 17, notes: ""},
  {course_id: 7, number: 12, par: 4, distance: 364, rating: 1, notes: ""},
  {course_id: 7, number: 13, par: 3, distance: 142, rating: 13, notes: ""},
  {course_id: 7, number: 14, par: 4, distance: 386, rating: 5, notes: ""},
  {course_id: 7, number: 15, par: 4, distance: 395, rating: 9, notes: ""},
  {course_id: 7, number: 16, par: 3, distance: 134, rating: 15, notes: ""},
  {course_id: 7, number: 17, par: 5, distance: 463, rating: 11, notes: ""},
  {course_id: 7, number: 18, par: 4, distance: 368, rating: 7, notes: ""},
  {course_id: 10, number: 1, par: 3, distance: 25, rating: 1, notes: ""},
  {course_id: 10, number: 2, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 3, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 4, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 5, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 6, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 7, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 8, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 9, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 10, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 11, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 12, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 13, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 14, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 15, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 16, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 17, par: nil, distance: nil, rating: nil, notes: nil},
  {course_id: 10, number: 18, par: nil, distance: nil, rating: nil, notes: nil},
])
Round.create!([
  {private: false, course_id: 1, holes: 18, score: nil, best: nil, notes: nil, user_id: 1},
  {private: false, course_id: 3, holes: 18, score: nil, best: nil, notes: nil, user_id: 3},
  {private: false, course_id: 2, holes: 18, score: nil, best: nil, notes: nil, user_id: 4},
  {private: false, course_id: 4, holes: 18, score: nil, best: nil, notes: nil, user_id: 3},
  {private: false, course_id: 6, holes: 18, score: nil, best: nil, notes: nil, user_id: 6},
  {private: false, course_id: 5, holes: 18, score: nil, best: nil, notes: nil, user_id: 1},
  {private: false, course_id: 7, holes: 18, score: nil, best: nil, notes: nil, user_id: 5},
  {private: false, course_id: 2, holes: 18, score: nil, best: nil, notes: nil, user_id: 2},
  {private: false, course_id: 1, holes: 18, score: nil, best: nil, notes: nil, user_id: 8},
  {private: false, course_id: 1, holes: 18, score: nil, best: nil, notes: nil, user_id: 3},
  {private: false, course_id: 3, holes: 18, score: nil, best: nil, notes: nil, user_id: 9},
  {private: false, course_id: 1, holes: 18, score: nil, best: nil, notes: nil, user_id: 11},
  {private: false, course_id: 2, holes: 18, score: nil, best: nil, notes: nil, user_id: 1},
  {private: false, course_id: 5, holes: 18, score: nil, best: nil, notes: nil, user_id: 10},
  {private: false, course_id: 6, holes: 18, score: nil, best: nil, notes: nil, user_id: 3}
])
RoundHole.create!([
  {round_id: 1, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 1, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 2, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 8, score: 6, strokes: 3, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 15, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 2, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 3, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 4, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 5, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 6, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 6, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 6, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 6, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 6, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 6, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 7, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 8, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 13, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 15, score: 6, strokes: 3, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 9, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 3, score: 6, strokes: 3, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 5, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 10, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 11, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 12, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 1, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 5, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 7, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 13, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 17, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 13, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 14, course_id: nil, number: 1, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 14, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 14, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 14, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 14, course_id: nil, number: 5, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 14, course_id: nil, number: 6, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 1, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 2, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 3, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 4, score: 3, strokes: 2, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 5, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 6, score: 7, strokes: 4, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 7, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 8, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 9, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 10, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 11, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 12, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 13, score: 4, strokes: 3, putts: 1, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 14, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 15, score: 5, strokes: 2, putts: 3, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 16, score: 4, strokes: 2, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 17, score: 5, strokes: 3, putts: 2, notes: "", course_hole_id: nil},
  {round_id: 15, course_id: nil, number: 18, score: 5, strokes: 4, putts: 1, notes: "", course_hole_id: nil}
])
